[tools]
java = "temurin-25.0.1+8.0.LTS"
clojure = "1.12.4.1582"
babashka = "1.12.213"
clj-kondo = "2026.01.19"
cljfmt = "0.15.6"
node = "24.13.0"
lefthook = "2.0.15"

[alias]
cljfmt = "asdf:https://github.com/b-social/asdf-cljfmt"
